import type { Workout } from "./types"
export interface TrainingPeaksAdapter { getWeek():Promise<Workout[]>; updateWorkout(id:string,change:string):Promise<void>; connectionState():Promise<"connected"|"mock"|"expired"> }
const week:Workout[]=[
{id:"mon",day:"MON",date:"Sep 14",sport:"Swim",title:"Easy technique",duration:"45 min",goal:"Stay relaxed and sharpen feel for the water.",details:"Warm Up:\n1 x (200 FS in Z2 + 100 Drill in Z2 + 20 secs rest).\n\nMain Set:\n6 x (100 FS in Z2 + 20 secs rest),\n4 x (50 Build in Z3 + 20 secs rest).\n\nWarm Down:\n1 x (200 Choice in Z2).",status:"completed",risk:"low",load:31},
{id:"tue",day:"TUE",date:"Sep 15",sport:"Bike",title:"Race power touch",duration:"1h 05m",goal:"Keep race power familiar without carrying fatigue forward.",details:"15 min easy · 3 × 8 min @ 240–250W · 4 min easy · 10 min cool down",status:"today",risk:"medium",load:54,recommendation:"Drop the three blocks by 10–15 watts after yesterday’s poor recovery score."},
{id:"wed",day:"WED",date:"Sep 16",sport:"Run",title:"Easy + strides",duration:"40 min",goal:"Keep cadence sharp while protecting freshness.",details:"30 min Z2 · 4 × 20 sec strides · full easy recovery",status:"upcoming",risk:"low",load:36},
{id:"thu",day:"THU",date:"Sep 17",sport:"Swim",title:"Race rhythm",duration:"50 min",goal:"Rehearse smooth race rhythm with controlled breathing.",details:"400 easy · 8 × 100 race rhythm · 200 choice",status:"upcoming",risk:"low",load:42},
{id:"fri",day:"FRI",date:"Sep 18",sport:"Recovery",title:"Rest day",duration:"—",goal:"Absorb the week and arrive fresh for Saturday.",details:"Walk and mobility only.",status:"upcoming",risk:"low",load:0},
{id:"sat",day:"SAT",date:"Sep 19",sport:"Bike",title:"Race rehearsal brick",duration:"1h 40m",goal:"Confirm pacing and fueling; finish with more available.",details:"Bike 75 min with 2 × 15 min race power · Run 20 min easy",status:"upcoming",risk:"medium",load:86},
{id:"sun",day:"SUN",date:"Sep 20",sport:"Run",title:"Easy aerobic",duration:"50 min",goal:"Keep this easy and finish the week feeling better.",details:"50 min Z2. No fast finish.",status:"upcoming",risk:"low",load:44}]
class MockAdapter implements TrainingPeaksAdapter { async getWeek(){return structuredClone(week)} async updateWorkout(id:string,change:string){await new Promise(r=>setTimeout(r,650));const w=week.find(x=>x.id===id);if(!w)throw new Error("Workout not found");w.changed=true;w.recommendation=change} async connectionState(){return "mock" as const} }
export const trainingPeaks:TrainingPeaksAdapter=new MockAdapter()
